name: Build Release

on:
  push:
    tags:
      - "v*"

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run deploy script
        run: |
          chmod +x deploy.sh
          ./deploy.sh --ci

      - name: Locate bundle
        id: bundle
        run: |
          ZIP_FILE=$(ls dist/*.zip)
          echo "bundle=$ZIP_FILE" >> "$GITHUB_OUTPUT"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.bundle.outputs.bundle }}
